language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "aws-webservice/gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ejjwa0563@gmail.com
