language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "cd aws-webservice ./gradlew build"

before_deploy:
    - cd aws-webservice
    - mkdir -p before-deploy
    - cp scripts/*.sh before-deploy
    - cp appspec.yml before-deploy
    - cp byuld.libs/*.jar before-deploy/
    - cd before-deploy && zip -r before-deploy 
    - cd ../ && mkdir -p deploy
    - mv before-deploy/before-deploy.zip deploy/aws-webservice.zip

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY  # Travis repo setting에 설정된 값
      secret_access_key: $AWS_SECRET_KEY
      bucket: jinny-deploy
      region: ap-northeast-2
      skip_cleanup: true
      acl: private    # zip 파일 접근을 private으로
      local_dir: deploy   # before_deploy에서 생성한 디렉토리 
      wait-until-deployed: true
    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY  # Travis repo setting에 설정된 값
      secret_access_key: $AWS_SECRET_KEY
      bucket: jinny-deploy
      key: aws-webservice.zip   # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: aws-webservice
      deployment_group: aws-webservice-group
      region: ap-northease-2
      wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ejjwa0563@gmail.com
